// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqDpJnUm2xv4xpsrvxRJrsQecH9l3wn3A',
    appId: '1:90606060097:web:44c79ebb74652a13da3cc0',
    messagingSenderId: '90606060097',
    projectId: 'ecombackend-a37b0',
    authDomain: 'ecombackend-a37b0.firebaseapp.com',
    storageBucket: 'ecombackend-a37b0.appspot.com',
    measurementId: 'G-1Y6ZV41510',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTRXWwUQyZAopsNVvCF5NTK7UOhSNlvfs',
    appId: '1:90606060097:android:963f15a772b3ffeeda3cc0',
    messagingSenderId: '90606060097',
    projectId: 'ecombackend-a37b0',
    storageBucket: 'ecombackend-a37b0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArHoqtB7gqL9xzNN60gJrhAeZ_RkfIcWA',
    appId: '1:90606060097:ios:1ec5675c6f3c16d6da3cc0',
    messagingSenderId: '90606060097',
    projectId: 'ecombackend-a37b0',
    storageBucket: 'ecombackend-a37b0.appspot.com',
    iosBundleId: 'com.example.ecommerceNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArHoqtB7gqL9xzNN60gJrhAeZ_RkfIcWA',
    appId: '1:90606060097:ios:0bb7830e06e3b007da3cc0',
    messagingSenderId: '90606060097',
    projectId: 'ecombackend-a37b0',
    storageBucket: 'ecombackend-a37b0.appspot.com',
    iosBundleId: 'com.example.ecommerceNew.RunnerTests',
  );
}
